[tox]
envlist = passagemath

[testenv:.pkg]
passenv =
    CPATH
    LIBRARY_PATH

[testenv:passagemath]
usedevelop = True
extras = passagemath, test

passenv =
    CPATH
    LIBRARY_PATH

commands =
    pytest

[pytest]
addopts = -s -vv
