name: Lint code
env:
  SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  CODE_DIR: /home/sage/zeroforcing
on:
  workflow_run:
    workflows:
      - Build and Test
    types:
      - completed
jobs:
  lint:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: zeroforcing-${{env.SHA}}
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/zeroforcing-${{env.SHA}}.tar
      - name: Run Docker image
        run: |
            echo "CONTAINER_ID=$(docker run -d zeroforcing:${SHA})" >> $GITHUB_ENV
      - name: Install lint requirements
        run: |
            docker exec --workdir "${CODE_DIR}" "${CONTAINER_ID}" sage -pip install '.[lint]'
      - name: Start Sage shell to find lint dep. executables & Lint Cython code
        run: |
            docker exec --workdir "${CODE_DIR}" "${CONTAINER_ID}" sage --sh -c 'find src -type f \( -iname \*.pyx -o -iname \*.pxd \) | xargs cython-lint'
